### ISSUE TITLE
Viewport Alignment Issue

### ISSUE THREAD

**Issue by thazell** [gtalarico/pyrevitplus#10]
I'm having an issue that the viewport alignment tool.  All the views have the same scopebox, but they aren't aligning.  I check to make sure the titleblocks were in the same location.  Here is my theory:  Grids, etc that extend beyond the crop region of a view aren't matching between the views. Thus the viewports have different center points. Thoughts?

Here's a proposed solution.  
Can we use "getboxoutline" method to store the outline of the view and when using "set view port center" if the box outline doesn't match the one that was used when storing it would just give the user a warning stating they can't use the tool?

Thoughts?

**Comment by gtalarico** [comment]
Thanks @thazell
this would be a good check to add. 
But If I am not mistaken, @eirannejad 's copy/past state can handle this (viewport placement), and it's smarter as it uses the viewport coordinate system instead of just bbox of viewport - need to confirm, though.
If that's the case, I might deprecate this tool

**Comment by thazell** [comment]
Looks like @eirannejad has already looked into these: http://eirannejad.github.io/pyRevit/pyrevit/update/2016/08/12/copypasteviewporttools.html

**Comment by gtalarico** [comment]
Fixed on https://github.com/gtalarico/pyrevitplus/commit/7359c062cc945118cb7271a09a8225f091c4b1f8
